name: "Deploy to AWS"
on:
  push:
    branches: [ main ]  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Using Node.js 20 as required by react-router-dom
          
      - name: Install dependencies
        run: |
          cd react
          npm install
          
      - name: Build React app
        run: |
          cd react
          npm run build
          
      - name: Deploy and Start application
        run: |
          cd react
          pm2 serve dist 3000 --name "react-app" --spa
