name: "Deploy to AWS"

#trigger the workflow from the github ui
on : workflow_dispatch

jobs:
    deploy: 
      runs-on: self-hosted
      steps:
         -  name: "setup node.js"
            uses: actions/setup-node@v4
            with : 
              node-verion: "20"

         - name: "checkout out"
           uses : actions/checkout@v2

         - name: "install depemdemcies"
           run: npm install

         - name: "install pm2 globally"
           run: sudo npm install pm2 -g

         - name: "run the tests"
           run: npm test 

         - name: "Deploy to AWS"
           run: |
            npm run build
            pm2 serve build 3000 --name "react-app"
